name = "omp_offloading"
version = "0.1.0"
license = "license"
author = "Jorge Galvez Vallejo"
maintainer = "jorgegalvez1694@gmail.com"
copyright = "Copyright 2025, Jorge Galvez Vallejo"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
test = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
[dependencies]
pic = { git = "https://github.com/JorgeG94/pic.git", branch = "chore/noblas"}
